worker_processes  1;
daemon on;
master_process off;
error_log /opt/packages/modules/zstd-nginx-module/t/servroot-static/logs/error.log debug;
pid       /opt/packages/modules/zstd-nginx-module/t/servroot-static/logs/nginx.pid;
env MOCKEAGAIN_VERBOSE;
env MOCKEAGAIN;
env MOCKEAGAIN_WRITE_TIMEOUT_PATTERN;
env LD_PRELOAD;
env LD_LIBRARY_PATH;
env DYLD_INSERT_LIBRARIES;
env DYLD_FORCE_FLAT_NAMESPACE;
#env LUA_PATH;
#env LUA_CPATH;



http {
    access_log /opt/packages/modules/zstd-nginx-module/t/servroot-static/logs/access.log; client_body_temp_path /opt/packages/modules/zstd-nginx-module/t/servroot-static/client_body_temp; proxy_temp_path /opt/packages/modules/zstd-nginx-module/t/servroot-static/proxy_temp; fastcgi_temp_path /opt/packages/modules/zstd-nginx-module/t/servroot-static/fastcgi_temp;  
    #access_log off;

    default_type text/plain;
    keepalive_timeout  68000ms;


    server {
        listen          1984;
        #placeholder
        server_name     'localhost';
        
        client_max_body_size 30M;
        #client_body_buffer_size 4k;

        # Begin preamble config...

        # End preamble config...

        # Begin test case config...
    location /test2 {
        zstd_static off;
        root ../../t/suite;
    }

        # End test case config.

        location / {
            root /opt/packages/modules/zstd-nginx-module/t/servroot-static/html;
            index index.html index.htm;
        }
    }
}



#timer_resolution 100ms;

events {
    accept_mutex off;

    worker_connections  64;
}
env ASAN_OPTIONS;
env MOCKNOEAGAIN_VERBOSE;
env MOCKNOEAGAIN;
